input
js-tasks-ru/htmlcss-20230714_takeshi1 pull request #21
Opened 2023-08-13 15:39 UTC by Takeshiii

2023-08-13 15:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-14 21:49 UTC, GSemikozov requested changes

2023-08-14 21:49 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.inputs {
лишнее

2023-08-14 21:49 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          <svg class="icon input__icon">
в разметке будет сразу 2 иконки, по умолчанию - они скрыты, а показывать будем привязываясь к модификатору

2023-08-15 08:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-15 08:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-15 08:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-15 08:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-15 16:01 UTC, GSemikozov approved these changes

2023-08-18 11:29 UTC, GSemikozov approved these changes

2023-08-18 11:29 UTC, merged