add accordion
js-tasks-ru/htmlcss-20230714_takeshi1 pull request #4
Opened 2023-07-23 15:50 UTC by Takeshiii

2023-07-23 15:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-25 05:36 UTC, GSemikozov requested changes

2023-07-25 05:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details:nth-child(3) {
просто :last-child

2023-07-25 05:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  /* Я это оставил, но что-то не работает как ни крутил */
это часть дз :)

гугл первой ссылкой запроса дает ответ:

```
summary {
  list-style: none;
}
```

2023-07-25 05:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
лучше обработать этот кейс как accordion__details[open] { padding-bottom: 32px; }

2023-07-25 05:36 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <details class="accordion__details">
элементы не могут существовать вне своего родителя, все секции надо завернуть в общий div с классом accordion

2023-07-25 08:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-25 08:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-26 05:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-26 06:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-26 10:46 UTC, GSemikozov requested changes

2023-07-26 10:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary {
.accordion__summary

2023-07-26 12:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-27 11:39 UTC, GSemikozov approved these changes

2023-07-27 11:39 UTC, merged